const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');

// Ensure dist directory exists
if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
}

function bundle(files, outputName, isCss = false) {
    const outputPath = path.join(DIST_DIR, outputName);
    let output = isCss 
        ? `/* Unified Styles Bundle — Built at: ${new Date().toISOString()} */\n\n`
        : `// Auto-generated by build.js — do not edit directly\n// Built at: ${new Date().toISOString()}\n\n`;

    for (const file of files) {
        const filePath = path.join(SRC_DIR, file);
        if (!fs.existsSync(filePath)) {
            console.error(`ERROR: Missing file: ${filePath}`);
            continue;
        }
        const content = fs.readFileSync(filePath, 'utf-8');
        output += isCss ? `/* ─── ${file} ─── */\n` : `// ─── ${file} ─── \n`;
        output += content;
        output += '\n\n';
    }

    fs.writeFileSync(outputPath, output, 'utf-8');
    console.log(`✅ Build complete: dist/${outputName} (${(fs.statSync(outputPath).size / 1024).toFixed(1)} KB)`);
}

// Bundle Content Scripts
bundle(['content/content.js'], 'content.js');
bundle(['content/docs-bridge.js'], 'docs-bridge.js');
bundle(['shared/theme.css', 'content/content.css'], 'content.css', true);

// Bundle Background Script
bundle(['background/background.js'], 'background.js');
