const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');

// Ensure dist directory exists
if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
}

function bundle(files, outputName, isCss = false) {
    const outputPath = path.join(DIST_DIR, outputName);
    let output = isCss 
        ? `/* Unified Styles Bundle — Built at: ${new Date().toISOString()} */\n\n`
        : `// Auto-generated by build.js — do not edit directly\n// Built at: ${new Date().toISOString()}\n\n`;

    for (const file of files) {
        const filePath = path.join(SRC_DIR, file);
        if (!fs.existsSync(filePath)) {
            console.error(`ERROR: Missing file: ${filePath}`);
            continue;
        }
        const content = fs.readFileSync(filePath, 'utf-8');
        output += isCss ? `/* ─── ${file} ─── */\n` : `// ─── ${file} ─── \n`;
        output += content;
        output += '\n\n';
    }

    fs.writeFileSync(outputPath, output, 'utf-8');
    console.log(`✅ Build complete: dist/${outputName} (${(fs.statSync(outputPath).size / 1024).toFixed(1)} KB)`);
}

function copyFile(srcRel, distRel) {
    const srcPath = path.join(SRC_DIR, srcRel);
    const distPath = path.join(DIST_DIR, distRel);
    if (fs.existsSync(srcPath)) {
        fs.copyFileSync(srcPath, distPath);
        console.log(`✅ Copied: dist/${distRel}`);
    }
}

// Bundle Content Scripts
bundle(['content/content.js'], 'content.js');
bundle(['content/docs-bridge.js'], 'docs-bridge.js');
bundle(['shared/theme.css', 'content/content.css'], 'content.css', true);

// Bundle Background Script (chunking + orchestration; no synthesis)
bundle(['shared/chunk.js', 'shared/cloudTts.js', 'background/background.js'], 'background.js');

// Bundle the Offscreen document with the Edge Neural TTS client.
// Synthesis lives here because declarativeNetRequest header rules are not applied
// to WebSocket upgrades started from a service worker (crbug.com/1285664).
bundle(['shared/chunk.js', 'shared/cloudTts.js', 'shared/edgeTts.js', 'shared/webSpeech.js', 'shared/exportPipeline.js', 'shared/exportStore.js', 'offscreen/offscreen.js'], 'offscreen.js');

// Copy Offscreen shell and Shared Assets
copyFile('offscreen/offscreen.html', 'offscreen.html');
copyFile('shared/voices.json', 'voices.json');

// Copy Icons and Assets
const distIconsDir = path.join(DIST_DIR, 'icons');
if (!fs.existsSync(distIconsDir)) {
    fs.mkdirSync(distIconsDir, { recursive: true });
}
['icon16.png', 'icon32.png', 'icon48.png', 'icon128.png', 'icon.svg', 'logo.svg'].forEach(iconFile => {
    copyFile(`icons/${iconFile}`, `icons/${iconFile}`);
});

const rootRules = path.join(__dirname, 'rules.json');
const distRules = path.join(DIST_DIR, 'rules.json');
if (fs.existsSync(rootRules)) {
    fs.copyFileSync(rootRules, distRules);
    console.log('✅ Copied: dist/rules.json');
}

